Contact form of Portofolio
SabaAhmad786/final-portofolio pull request #2
Opened 2022-09-27 16:57 UTC by SabaAhmad786

This is a finished portfolio mobile website. In this project, i work with my coding partner to create a contact form of the portofolio  In this project 
1) added linters
2) added HTML and CSS
kindly review my project

2022-09-27 18:04 UTC, mukhammadrizooff requested changes
Hi @SabaAhmad786, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 18:04 UTC, mukhammadrizooff commented on index.html
> +                           <form action="contact-form" method="post">
- [ ] [REQUIRED] Good job so far! Your `Form` should use the `action` and `method` attribute to integrate with [formspree service](https://formspree.io/html). You have used `action` and `method` in form but you made some mistake in value given to `action`, Please use formspree to give value to `action`!  `[HINT]` The `action` value should be similar to `https://formspree.io/f/{form_id}`

![image](https://user-images.githubusercontent.com/63915024/192602523-d888d314-b321-4fce-9745-7a385bffcb04.png)

2022-09-27 19:54 UTC, aimalamiri requested changes
Hi @SabaAhmad786, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 19:54 UTC, aimalamiri commented on index.html
> +                           <form action="https://formspree.io/forms" method="post">
Good job, but as the previous reviewer requested, please make sure to use a proper form link. For this visit the [Formspree](https://formspree.io/html) website and create an account. You'll be able to create a form once you log in.

It throws an error currently for the incorrect form link.

![image](https://user-images.githubusercontent.com/34779928/192621261-5230fad7-a6e5-43a8-8a80-0dfcc71629a4.png)

2022-09-27 19:54 UTC, aimalamiri commented on index.html
> +              </section>
[Optional] In order to make your webpage look better, it's important to follow the Figma template. So please try to remove the extra space from the right.

![image](https://user-images.githubusercontent.com/34779928/192622605-0333a190-33e0-4eba-abbf-f2d252bb3426.png)

2022-09-27 19:54 UTC, aimalamiri commented on index.html
> +                       If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it
[Optional] It looks great, but it's important to follow the Figma template. So please try to follow the same Figma font size.

![image](https://user-images.githubusercontent.com/34779928/192621868-4b187a5a-9f9f-46b8-82b5-5f7929acb817.png)

2022-09-28 08:12 UTC, levy002 approved these changes
Hi @SabaAhmad786 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

## Status: APPROVED 🔥 🔥 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 08:12 UTC, levy002 commented on style.css
> +}
- [OPTIONAL] I highly recommend removing the padding on this container in order to look like the provided Figma design. :wink: 

    - ### Your design (with padding)

   ![image](https://user-images.githubusercontent.com/87197412/192725175-5decf6a2-bb21-4b29-9c9c-f616827236a7.png)

    - ### Your design (without padding)

   ![image](https://user-images.githubusercontent.com/87197412/192725123-19cdb2d5-d897-45c2-b0fb-3cd8d0b115dd.png)

2022-09-28 08:21 UTC, merged